### ISSUE TITLE
Data in log view is incorrect

### ISSUE THREAD

**Issue by jaraco** [yougov/velociraptor#208]
Somewhat related to #174, I'm encountering another issue trying to review the logs in Velociraptor. Consider this screen shot:

![image](https://cloud.githubusercontent.com/assets/308610/21013875/9a724ec6-bd29-11e6-9adf-69379ea8ade8.png)

I've navigated to page 4 of the logs, then filtered by Swarms and hit apply. But what appears are events in the future. The date at the top, Thu Dec 8 7:17 PM (should be 19:17) hasn't happened yet. It's currently 14:31 UTC on Dec 8.

**Comment by lbolla** [comment]
Very strange. We generate the page server side, here: https://github.com/yougov/vr.server/blob/master/vr/server/templates/log.html#L14

Also, it works for me (from London). See screenshot (for the same set of events as above):
![screenshot from 2016-12-09 10 50 06](https://cloud.githubusercontent.com/assets/20991/21046836/7bc747e4-bdfe-11e6-89c4-c043e7e9c2e6.png)

**Comment by lbolla** [comment]
Fixed 24-hours formatting in https://github.com/yougov/vr.server/commit/ce90abf6c5c9ed59ef075584abeae8b6329a112b

**Comment by lbolla** [comment]
Oh, I just noticed that sorting if obviously wrong: it jumps from "1.12 PM" to "12:38 PM".

**Comment by lbolla** [comment]
Fixed in https://github.com/yougov/vr.server/commit/e11128e52daf6a065cc983d97cc84722a1619f0c

The problem is that the filtering was done client-side, which involved creating JS Date objects on the user browser which can be using any timezone. Instead, I got rid of all the client-side code and just implemented the filtering server-side (which as the added benefit of allowing deep-linking).
